parameters:
- name: tailscaleKey
  displayName: TailScale Pre-auth Key
  type: string
  default: tskey-123replaceme321
- name: tailscaleRoutes
  displayName: Subnet routes for this node
  default: 192.168.64.0/24,10.64.0.0/16
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - ubuntu-latest
  - ubuntu-20.04

# I'd like to run this manually
trigger: none

jobs:
- job: deploy
  displayName: Deploy to Azure
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - script: sed -i "s|__REPLACEKEY__|${{ parameters.tailscaleKey }}|g; s|__REPLACEROUTES__|${{ parameters.tailscaleRoutes }}|g" artifacts/cloud-init.txt
    displayName: Correct cloud-init.txt
  - script: cat artifacts/cloud-init.txt
  